### ISSUE TITLE
Can't search for this attendee by name/email/etc. in the admin panel. 

### ISSUE THREAD

**Issue by jeddc** [nickyhajal/wds-admin#18]
Haley Donovan has all the right credentials in sequel and stripe. However I can't search or pull up her record at all in the admin panel. I've had similar issues where I wasn't able to pull someone up with their name but was able to pull them up with their email. She's the first that I couldn't pull up at all. 
<img width="823" alt="screen shot 2018-05-25 at 8 29 50 am" src="https://user-images.githubusercontent.com/11277509/40552940-0edde052-5ff6-11e8-9071-f2b36c79223a.png">

**Comment by nickyhajal** [comment]
Should be fixed 👍
