### ISSUE TITLE
Profile/Avatar pics not displaying correctly

### ISSUE THREAD

**Issue by jeddc** [nickyhajal/wds-admin#22]
http://admin.wds.fm/person/jamesareg@hotmail.com

<img width="572" alt="screen shot 2018-05-29 at 9 48 16 am" src="https://user-images.githubusercontent.com/11277509/40673123-b451af5a-6325-11e8-83c8-172aca988fc1.png">

**Comment by nickyhajal** [comment]
I'd renamed this "Rotate avatars from admin" here => #20 

Will add that ability soon!
